####
# Automation Meta-Data: KV Namespaces
#
# This worker relies on the following KV namespaces.
#
# KV Name: gmtww_users
# KV Binding: USERS
# KV Description: This KV is used to hold the list of registered users.
####



name = "gmtww-api-register-user"
main = "main.js"
compatibility_date = "2023-05-18"
