####
# Automation Meta-Data: KV Namespaces
#
# This worker relies on the following key value namespaces.
#
# KV Name: kv_gmtww_l14_storage
# KV Binding: GMTWW_STORAGE
# KV Description: This KV is used to hold data for API.
####

name = "gmtww-api-l14-product-list"
main = "main.js"
compatibility_date = "2023-05-18"
