####
# Automation Meta-Data: KV Namespaces
#
# This worker relies on the following key value namespaces.
#
# KV Name: kv_gmtww_l14_products
# KV Binding: GMTWW_PRODUCTS
# KV Description: This KV is used to hold all of the product data.
####

name = "gmtww-api-l14-product-list"
main = "main.js"
compatibility_date = "2023-05-18"
