name = "gmtww-token"
compatibility_date = "2023-05-18"

[[kv_namespaces]]
binding = "GMTWW_USERS"
id = "acc167cec159403bbec7077851aafc5b"
preview_id = "acc167cec159403bbec7077851aafc5b"

[[kv_namespaces]]
binding = "GMTWW_TOKENS"
id = "070c9f95edd64c8e8e3ae9a15cce139c"
preview_id = "070c9f95edd64c8e8e3ae9a15cce139c"
