####
# Automation Meta-Data: KV Namespaces
#
# This worker relies on the following KV namespaces.
#
# KV Name: gmtww_storage
# KV Binding: STORAGE
# KV Description: This KV is used to hold data for the API.
####

name = "gmtww-api-product-list"
main = "main.js"
compatibility_date = "2023-05-18"
