name = "gmtww-checkout"
main = "main.js"
compatibility_date = "2023-05-18"

[[kv_namespaces]]
binding = "GMTWW_STORAGE"
id = "656489f7ee2f46dfbfb89c2a7bcc343d"
preview_id = "656489f7ee2f46dfbfb89c2a7bcc343d"

[vars]

# This worker relies on the following secret vars.
#
# - STRIPE_API_KEY: A Stripe API key. The account associated with this key
# will be the account that all payments are processed through.
#
# Use either of the methods below to add the secret vars to the worker once it
# is deloyed.
#
# Add/Update Individual Secret Vars Command
# echo "<value>" | npx wrangler secret put <key> --config "<worker-config>"
#
# Add/Update Multiple Secret Vars Command
# *All secret key value pairs need to in a JSON file at the top level.
# npx wrangler secret:bulk "<secret-json-file>" --config "<worker-config>"
