name = "gmtww-checkout"
main = "main.js"
compatibility_date = "2023-05-18"

[[kv_namespaces]]
binding = "GMTWW_STORAGE"
id = "656489f7ee2f46dfbfb89c2a7bcc343d"
preview_id = "656489f7ee2f46dfbfb89c2a7bcc343d"

[vars]

# This worker relies on the secret vars listed below.
#
# Secret Var: STRIPE_API_KEY
# A Stripe API key. The account associated with this key will be the account
# that all payments are processed through.

