####
# Automation Meta-Data: KV Namespaces
#
# This worker relies on the following KV namespaces.
#
# KV Name: gmtww_storage
# KV Binding: STORAGE
# KV Description: This KV is used to hold data for the API.
####

####
# Automation Meta-Data: Secret Variables
#
# This worker relies on the following secret variables.
#
# Secret Variable Name: STRIPE_API_KEY
# Secret Variable Description: A Stripe API key. The account associated with
# this key will be the account that all payments are processed through.
####

name = "gmtww-api-checkout"
main = "main.js"
compatibility_date = "2023-05-18"
